=== Nellix/Distributed-Programming-II/3_LAB/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/nffgInfo" xmlns:tns="http://www.example.org/nffgInfo" elementFormDefault="qualified">

<element name="NffgService" type="tns:NffgServiceType">
	<unique name="nffgId">
		<selector xpath="Nffgs/Nffgs"/>
		<field xpath="@name"/>
	</unique>
</element>




<complexType name="NffgServiceType">
	<sequence>
		<element name="Nffgs">
			<complexType>
				<sequence>
					<element name="Nffg" type="tns:NffgType" minOccurs="0" maxOccurs="unbounded">
							<key name="nodeId">
								<selector xpath="tns:Nodes/tns:Node"/>
								<field xpath="@name"/>
							</key>
							<keyref name="linkDestinationNode" refer="tns:nodeId">
								<selector xpath="Nodes/Node/Links/Link/destinationNode"/>
								<field xpath="@name"/>
							</keyref>
							<keyref name="reachabilitySource" refer="tns:nodeId">
								<selector xpath="Policies/ReachabilityPolicy/SrcNode"/>
								<field xpath="@name"/>
							</keyref>
							<keyref name="reachabilityDestination" refer="tns:nodeId">
								<selector xpath="Policies/ReachabilityPolicy/DstNode"/>
								<field xpath="@name"/>
							</keyref>
							<keyref name="traversalSource" refer="tns:nodeId">
								<selector xpath="Policies/TraversalPolicy/SrcNode"/>
								<field xpath="@name"/>
							</keyref>
							<keyref name="traversalDestination" refer="tns:nodeId">
								<selector xpath="Policies/TraversalPolicy/DstNode"/>
								<field xpath="@name"/>
							</keyref>
							<unique name="linkName">
								<selector xpath="Nodes/Node/Links/Link"/>
								<field xpath="@name"/>
							</unique>
					</element>
				</sequence>
			</complexType>
		</element>
	</sequence>
</complexType>


<complexType name="NffgType">
	<complexContent>
		<extension base="tns:nameEntityType">
			<sequence>
				<element name="UpdateTime" type="dateTime" minOccurs="1"></element>
				<element name="Nodes">
					<complexType>
						<sequence>
							<element name="Node" type="tns:NodeType" minOccurs="0" maxOccurs="unbounded">								
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="Policies">
					<complexType>
						<sequence>
							<element name="ReachabilityPolicy" type="tns:ReachabilityPolicyType" minOccurs="0" maxOccurs="unbounded"></element>
							<element name="TraversalPolicy" type="tns:TraversalPolicyType" minOccurs="0" maxOccurs="unbounded"></element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</extension>
	</complexContent>
</complexType>


<complexType name="PolicyType">
	<complexContent>
		<extension base="tns:nameEntityType">
			<sequence>
				<element name="VerificationResult" type="tns:VerificationResultType" minOccurs="0"></element>
			</sequence>
			<attribute name="PolicyResult" type="boolean" use="required"/>
		</extension>
	</complexContent>
</complexType>


<complexType name="ReachabilityPolicyType">
	<complexContent>
		<extension base="tns:PolicyType">
			<sequence>
				<element name="SrcNode" type="tns:nameEntityType" minOccurs="1"></element>
				<element name="DstNode" type="tns:nameEntityType" minOccurs="1"></element>
			</sequence>
		</extension>
	</complexContent>
</complexType>


<complexType name="TraversalPolicyType">
	<complexContent>
		<extension base="tns:ReachabilityPolicyType">
			<sequence>
				<element name="TraversedFTypes">
					<complexType>
						<sequence>
							<element name="FType" type="tns:FunctionalType" minOccurs="0" maxOccurs="unbounded"></element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</extension>
	</complexContent>
</complexType>


<complexType name="VerificationResultType">
	<sequence>
		<element name="VerificationResult" type="boolean"></element>
		<element name="VerificationMessage" type="string"></element>
		<element name="VerificationTime" type="dateTime"></element>
	</sequence>
</complexType>

<complexType name="NodeType">
	<complexContent>
		<extension base="tns:nameEntityType">
			<sequence>
				<element name="Type" type="tns:FunctionalType"></element>
				<element name="Links">
					<complexType>
						<sequence>
							<element name="Link" type="tns:LinkType" minOccurs="0" maxOccurs="unbounded"></element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</extension>
	</complexContent>
</complexType>

<complexType name="nameEntityType">
	<attribute name="name" type="string" use="required"></attribute>
</complexType>

<complexType name="LinkType">
	<complexContent>
		<extension base="tns:nameEntityType">
			<sequence>
				<element name="destinationNode" minOccurs="1" type="tns:nameEntityType"></element>
			</sequence>
		</extension>
	</complexContent>
</complexType>
	
<simpleType name="FunctionalType" final="restriction">
		<restriction base="string">
			<enumeration value="FW"/>
			<enumeration value="DPI"/>
			<enumeration value="NAT"/>
			<enumeration value="SPAM"/>
			<enumeration value="CACHE"/>
			<enumeration value="VPN"/>
			<enumeration value="WEB_SERVER"/>
			<enumeration value="WEB_CLIENT"/>
			<enumeration value="MAIL_SERVER"/>
			<enumeration value="MAIL_CLIENT"/>
		</restriction>
</simpleType>
	
	
</schema>

=== Nellix/Distributed-Programming-II/1_LAB/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<NffgService xmlns="http://www.example.org/nffgInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/nffgInfo nffgInfo.xsd">
    <Nffgs>
        <Nffg name="Nffg4">
            <UpdateTime>2016-09-25T20:26:20.000+02:00</UpdateTime>
            <Nodes>
                <Node name="FW1">
                    <Type>FW</Type>
                    <Links>
                        <Link name="Link28">
                            <destinationNode name="NAT7"/>
                        </Link>
                        <Link name="Link63">
                            <destinationNode name="MAILSERVER1"/>
                        </Link>
                        <Link name="Link61">
                            <destinationNode name="MAILSERVER2"/>
                        </Link>
                    </Links>
                </Node>
                <Node name="MAILSERVER2">
                    <Type>MAIL_SERVER</Type>
                    <Links>
                        <Link name="Link10">
                            <destinationNode name="VPN3"/>
                        </Link>
                        <Link name="Link47">
                            <destinationNode name="CACHE4"/>
                        </Link>
                    </Links>
                </Node>
          </Nodes>
            <Policies>
                <ReachabilityPolicy PolicyResult="false" name="Policy66">
                    <VerificationResult>
                        <VerificationResult>true</VerificationResult>
                        <VerificationMessage>Policy verificarion result true</VerificationMessage>
                        <VerificationTime>2016-09-25T13:52:20.000+02:00</VerificationTime>
                    </VerificationResult>
                    <SrcNode name="WEBCLIENT0"/>
                    <DstNode name="MAILSERVER2"/>
                </ReachabilityPolicy>
                <ReachabilityPolicy PolicyResult="false" name="Policy64">
                    <SrcNode name="WEBCLIENT0"/>
                    <DstNode name="WEBSERVER5"/>
                </ReachabilityPolicy>
            </Policies>
        </Nffg>
     </Nffgs>
</NffgService>
