=== Nellix/Distributed-Programming-II/1_LAB/dtd/nffgInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT nffgInfo (Nffgs)>
<!ELEMENT Nffgs ((Nffg)*)>

<!ELEMENT Nffg (UpdateTime, Nodes, Policies)>
<!ATTLIST Nffg
	name CDATA #REQUIRED >

<!ELEMENT updateTime (#PCDATA)>
<!ELEMENT Nodes ((Node)*)>

<!ELEMENT Node (Links)>
<!ATTLIST Node
	funcType (FW|DPI|NAT|SPAM|CACHE|VPN|WEB_SERVER|WEB_CLIENT|MAIL_SERVER|MAIL_CLIENT) #REQUIRED
	name CDATA #REQUIRED >

<!ELEMENT Policies ((ReachabilityPolicy)*, (TraversalPolicy)*)>

<!ELEMENT ReachabilityPolicy (((verificationResult)?), (sourceNode, destinationNode))>
<!ATTLIST ReachabilityPolicy
	PolicyResult (0|1) #REQUIRED
	name CDATA #REQUIRED >

<!ELEMENT TraversalPolicy ((((verificationResult)?), (sourceNode, destinationNode)), (traversedFunctionalTypes))>
<!ATTLIST TraversalPolicy
	PolicyResult (0|1) #REQUIRED
	name CDATA #REQUIRED >

<!ELEMENT funcType (#PCDATA)>
<!ELEMENT Links ((Link)*)>

<!ELEMENT Link (destinationNode)>
<!ATTLIST Link
	name CDATA #REQUIRED >

<!ELEMENT destinationNode EMPTY>
<!ATTLIST destinationNode
	name CDATA #REQUIRED >

<!ELEMENT verificationResult ANY>

<!ELEMENT sourceNode EMPTY>
<!ATTLIST sourceNode
	name CDATA #REQUIRED >

<!ELEMENT traversedFunctionalTypes ((funcType)*)>
<!ELEMENT verificationResultMsg (#PCDATA)>
<!ELEMENT verificationTime (#PCDATA)>

=== Nellix/Distributed-Programming-II/1_LAB/dtd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE nffgInfo SYSTEM "nffgInfo.dtd" >
<nffgInfo>
<Nffgs>
    <Nffg name="Nffg4">
            <UpdateTime>2016-09-25T20:26:20.000+02:00</UpdateTime>
            <Nodes>
                <Node name="FW1" funcType="FW">
                    <Links>
                        <Link name="Link28">
                            <destinationNode name="NAT7"/>
                        </Link>
                        <Link name="Link63">
                            <destinationNode name="MAILSERVER1"/>
                        </Link>
                        <Link name="Link61">
                            <destinationNode name="MAILSERVER2"/>
                        </Link>
                    </Links>
                </Node>
                <Node name="MAILSERVER2" funcType="MAIL_SERVER">
                    <Links>
                        <Link name="Link10">
                            <destinationNode name="VPN3"/>
                        </Link>
                        <Link name="Link47">
                            <destinationNode name="CACHE4"/>
                        </Link>
                    </Links>
                </Node>
          </Nodes>
           <Policies>
                <ReachabilityPolicy PolicyResult="0" name="Policy64">
                    <sourceNode name="WEBCLIENT0"/>
                    <destinationNode name="WEBSERVER5"/>
                </ReachabilityPolicy>
            </Policies>
        </Nffg>
     </Nffgs>
</nffgInfo>
